<?php
$confidant_slider_sc = confidant_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $confidant_slider_sc ) && strpos( $confidant_slider_sc, '[' ) !== false && strpos( $confidant_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( confidant_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$confidant_anchor_icon = confidant_get_theme_option( 'front_page_title_anchor_icon' );
		$confidant_anchor_text = confidant_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $confidant_anchor_icon ) || ! empty( $confidant_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $confidant_anchor_icon ) ? ' icon="' . esc_attr( $confidant_anchor_icon ) . '"' : '' )
									. ( ! empty( $confidant_anchor_text ) ? ' title="' . esc_attr( $confidant_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $confidant_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$confidant_scheme = confidant_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $confidant_scheme ) && ! confidant_is_inherit( $confidant_scheme ) ) {
			echo ' scheme_' . esc_attr( $confidant_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( confidant_get_theme_option( 'front_page_title_paddings' ) );
		if ( confidant_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$confidant_css      = '';
		$confidant_bg_image = confidant_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $confidant_bg_image ) ) {
			$confidant_css .= 'background-image: url(' . esc_url( confidant_get_attachment_url( $confidant_bg_image ) ) . ');';
		}
		if ( ! empty( $confidant_css ) ) {
			echo ' style="' . esc_attr( $confidant_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$confidant_anchor_icon = confidant_get_theme_option( 'front_page_title_anchor_icon' );
		$confidant_anchor_text = confidant_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $confidant_anchor_icon ) || ! empty( $confidant_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $confidant_anchor_icon ) ? ' icon="' . esc_attr( $confidant_anchor_icon ) . '"' : '' )
									. ( ! empty( $confidant_anchor_text ) ? ' title="' . esc_attr( $confidant_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( confidant_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' confidant-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$confidant_css      = '';
			$confidant_bg_mask  = confidant_get_theme_option( 'front_page_title_bg_mask' );
			$confidant_bg_color_type = confidant_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $confidant_bg_color_type ) {
				$confidant_bg_color = confidant_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $confidant_bg_color_type ) {
				$confidant_bg_color = confidant_get_scheme_color( 'bg_color', $confidant_scheme );
			} else {
				$confidant_bg_color = '';
			}
			if ( ! empty( $confidant_bg_color ) && $confidant_bg_mask > 0 ) {
				$confidant_css .= 'background-color: ' . esc_attr(
					1 == $confidant_bg_mask ? $confidant_bg_color : confidant_hex2rgba( $confidant_bg_color, $confidant_bg_mask )
				) . ';';
			}
			if ( ! empty( $confidant_css ) ) {
				echo ' style="' . esc_attr( $confidant_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$confidant_caption = confidant_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $confidant_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $confidant_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $confidant_caption, 'confidant_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$confidant_description = confidant_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $confidant_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $confidant_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $confidant_description ), 'confidant_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( confidant_get_theme_option( 'front_page_title_button1_link' ) != '' || confidant_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						confidant_show_layout( confidant_customizer_partial_refresh_front_page_title_button1_link() );
						confidant_show_layout( confidant_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
